jobs:
  - name: backend_build_and_push
    type: runSh
    steps:
      - IN: backend_gitRepo
        showBuildStatus: true
      - IN: docker_registry_config
        switch: off
      - TASK:
          script:
            - IMAGE_TAG=$(echo $BACKEND_GITREPO_COMMIT | cut -c 1-5) && echo $IMAGE_TAG
            - IMAGE_NAME=$(shipctl get_resource_version_key "backend_image" "sourceName") && echo $IMAGE_NAME
            - pushd $(shipctl get_resource_state backend_gitRepo)
            - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
            - docker push "$IMAGE_NAME:$IMAGE_TAG"
            - |
              if [ "$BACKEND_GITREPO_IS_PULL_REQUEST" == false ] && [ "$BACKEND_GITREPO_BRANCH" == "master" ]; then
                echo "Update backend_image"
                shipctl post_resource_state "backend_image" "versionName" "$IMAGE_TAG"
                exit 0
              else
                echo "Dont't update backend_image"
                echo "$BACKEND_GITREPO_IS_PULL_REQUEST != false || $BACKEND_GITREPO_BRANCH != master"
              fi;
      - OUT: backend_image

  - name: frontend_build_and_push
    type: runSh
    steps:
      - IN: frontend_gitRepo
        showBuildStatus: true
      - IN: docker_registry_config
        switch: off
      - TASK:
          runtime:
            container: false
          script:
            - IMAGE_TAG=$(echo $FRONTEND_GITREPO_COMMIT | cut -c 1-5) && echo $IMAGE_TAG
            - IMAGE_NAME=$(shipctl get_resource_version_key "frontend_image" "sourceName") && echo $IMAGE_NAME
            - pushd $(shipctl get_resource_state frontend_gitRepo)
            - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
            - docker push "$IMAGE_NAME:$IMAGE_TAG"
            - |
              if [ "$FRONTEND_GITREPO_IS_PULL_REQUEST" == false ] && [ "$FRONTEND_GITREPO_BRANCH" == "master" ]; then
                echo "Update frontend_image"
                shipctl post_resource_state "frontend_image" "versionName" "$IMAGE_TAG"
                exit 0
              else
                echo "Dont't update frontend_image"
                echo "$FRONTEND_GITREPO_IS_PULL_REQUEST != false || $FRONTEND_GITREPO_BRANCH != master"
              fi;
      - OUT: frontend_image

  - name: terraform
    type: runSh
    steps:
      - IN: infrastructure_masterRepo
      - IN: frontend_image
      - IN: backend_image
      - IN: dnsimple_env
        switch: off
      - IN: s3_env
        switch: off
      - IN: yandex_env
        switch: off
      - IN: db_env
        switch: off
      - IN: backend_secret_key_env
        switch: off
      - IN: docker_swarm_ssh
        switch: off
      - IN: dhparams
        switch: off
      - IN: qtickets_env
        switch: off
      - IN: backend_sentry_env
        switch: off
      - IN: frontend_sentry_env
      - TASK:
          script:
            - pushd $INFRASTRUCTURE_MASTERREPO_STATE/terraform
            - terraform init
            - |
              export TF_INPUT=0
              export TF_VAR_docker_swarm_ssh_key_public=$DOCKER_SWARM_SSH_PUBLIC_KEY_PATH
              export TF_VAR_docker_swarm_ssh_key_private=$DOCKER_SWARM_SSH_PRIVATE_KEY_PATH
              export TF_VAR_domain=krd.dev
              export TF_VAR_frontend_image_name=$FRONTEND_IMAGE_SOURCENAME
              export TF_VAR_frontend_image_version=$FRONTEND_IMAGE_VERSIONNAME
              export TF_VAR_backend_image_name=$BACKEND_IMAGE_SOURCENAME
              export TF_VAR_backend_image_version=$BACKEND_IMAGE_VERSIONNAME
              export TF_VAR_backend_secret_key=$BACKEND_SECRET_KEY
              export TF_VAR_backend_db_name=$DB_NAME
              export TF_VAR_backend_db_user=$DB_USER
              export TF_VAR_backend_db_password=$DB_PASSWORD
              export TF_VAR_backend_sentry_dsn=$BACKEND_SENTRY_DSN
              export TF_VAR_frontend_sentry_dsn=$FRONTEND_SENTRY_DSN
              export TF_VAR_frontend_sentry_token=$FRONTEND_SENTRY_TOKEN
              export TF_VAR_db_host=$DB_HOST
              export TF_VAR_db_port=$DB_PORT
              export TF_VAR_certbot_email=help@krddevdays.ru
              export TF_VAR_dhparams=$DHPARAMS_KEYPATH
              export TF_VAR_qtickets_endpoint=$QTICKETS_ENDPOINT
              export TF_VAR_qtickets_token=$QTICKETS_TOKEN
              export TF_VAR_qtickets_secret=$QTICKETS_SECRET
            - terraform plan -out=terraform.plan
            - terraform apply -auto-approve terraform.plan
            - popd
